### ISSUE TITLE
Not checking all lease entries

### ISSUE THREAD

**Issue by hillezzz** [ccmarris/nios_fixed_addr_util#1]
In the _get_lease_info_ function you construct a get request for only one lease, but a single IP address can have multiple lease entries. The CLTT for the leases (for the same IP address) it not guaranteed to be the same.
The fix should be to retrieve them all for a given IP address and go through them to find the newest CLTT.

**Comment by ccmarris** [comment]
Agreed, I've enhanced the check_in_use() method to check for multiple leases, but also if the match_client is MAC_ADDRESS I am verifying the lease is for the same Mac/hardware address. (v0.1.2) Please verify that this appears to be working in your environment as expected. Thank you for the feedback.

**Comment by ccmarris** [comment]
By the way I have also updated the output to support CSV (to file) or table to console.

**Comment by ccmarris** [comment]
Please re-open if you see any issues
